## Basic Configuration

baseurl = "https://tobiasweede.github.io/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

    contentdir = "content"
    layoutdir = "layouts"
    publishdir = "docs"

    author = "Tobias Weiss"
    title = "Tobias Weiss"

    theme = "tobi-goa"

    ## Hugo Built-in Features
    disqusShortname = "https-tobiasweede-github-io" # Comment out to disable Disqus.
    googleAnalytics = "XYZ"
    enableRobotsTXT = true

    ## Site Settings
    [params]
    author = "Tobias Weiss"
    intro = "(IT) enthusiast"
    description = "@Giessen, DE"
    authorimage = "me_wanted_big.png"
    dateformat = "Jan 2, 2006"

    ## Site Meta Settings
    [params.meta]
    description = "Personal page"
    keywords = "it,guitar,biking,jogging,hugo"

    ## Social Accounts
    [params.social]
    github = "tobiasweede"
    #instagram = "<username>"
    #linkedin = "<username>"
    #twitter = "<username>"
    #facebook = "<username>"
    #google = "<username>"
    #stackoverflow = "<username>"
    email = "spam@tobias-weiss.org"

    ## Extras
    [params.extra]
    copyright = "© 2022. Tobias Weiss. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
    poweredby = false
    hightlightjs = true

    ## Main Menu
    [[menu.main]]
        name = "about"
        identifier = "about"
        weight = 100
        url = "/about/"
    #[[menu.main]]
    #    name = "blog"
    #    identifier = "blog"
    #weight = 100
    #url = "/blog/"
    [[menu.main]]
        name = "pgp"
        weight = 200
        identifier = "pgp"
        url = "/pgp/"
    #[[menu.main]]
    #    name = "what happend to the old page?"
    #    weight = 300
    #    identifier = "hugo"
    #    url = "/hugo/"
