## Basic Configuration

baseurl = "https://tobias-weiss-ai-xr.github.io/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

    contentdir = "content"
    layoutdir = "layouts"
    publishdir = "docs"

    author = "Tobias Weiss"
    title = "Tobias Weiss"

    theme = "tobi-goa"

    ## Hugo Built-in Features
    disqusShortname = "https-tobias-weiss-ai-xr-github-io" # Comment out to disable Disqus.
    googleAnalytics = "XYZ"
    enableRobotsTXT = true

    ## allow raw HTML
    ## https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted
    [markup]
        [markup.goldmark]
            [markup.goldmark.renderer]
                unsafe = true

    ## Site Settings
    [params]
    author = "Tobias Weiß"
    intro = "AI & XR enthusiast"
    description = "@Giessen, DE"
    authorimage = "me_thumb.jpeg"
    dateformat = "Jan 2, 2006"

    ## Site Meta Settings
    [params.meta]
    description = "Personal homepage"
    keywords = "ai,it,guitar,biking,jogging,hugo,xr,ar,vr"

    ## Social Accounts
    [params.social]
    github = "tobias-weiss-ai-xr"
    #instagram = "tobias_weiss_ai_xr"
    linkedin = "tobias-weiss-ai-xr"
    #twitter = "<username>"
    #facebook = "<username>"
    #google = "<username>"
    #stackoverflow = "<username>"
    email = "spam@tobias-weiss.org"

    ## Extras
    [params.extra]
    copyright = "© 2025. Tobias Weiss. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
    poweredby = false
    hightlightjs = true

    ## Main Menu
    [[menu.main]]
        name = "curriculum vitae"
        identifier = "cv"
        weight = 100
        url = "/cv/"
    [[menu.main]]
        name = "personal story"
        identifier = "personal story"
        weight = 200
        url = "/story/"
    [[menu.main]]
        name = "photo gallery"
        identifier = "gallery"
    weight = 300
    url = "/gallery/"
    [[menu.main]]
        name = "pretty good privacy"
        weight = 400
        identifier = "pgp"
        url = "/pgp/"
    #[[menu.main]]
    #    name = "Extended Reality"
    #    weight = 200
    #    identifier = "xr"
    #    url = "/xr/"
    #[[menu.main]]
    #    name = "wiki "
    #    identifier = "wiki"
    #    weight = 500
    #    url = "https://tobias-weiss.org/wiki"
    #[[menu.main]]
    #    name = "what happend to the old page?"
    #    weight = 300
    #    identifier = "hugo"
    #    url = "/hugo/"
